import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#a8c4f4",
        "on-primary": "#00315a",
        "primary-container": "#2a4d7a",
        "on-primary-container": "#bfceef",
        "primary-fixed-dim": "#5c7aad",
        "secondary": "#b09b7e",
        "on-secondary": "#2d1700",
        "secondary-container": "#483016",
        "on-secondary-container": "#ffdab9",
        "secondary-fixed": "#ffab6c",
        "secondary-fixed-dim": "#c4915a",
        "surface": "#0d0d0d",
        "on-surface": "#d4d0cc",
        "surface-dim": "#111111",
        "surface-bright": "#0d0d0d",
        "surface-container-lowest": "#000000",
        "surface-container-low": "#111111",
        "surface-container": "#161616",
        "surface-container-high": "#1e1e1e",
        "surface-container-highest": "#262626",
        "surface-variant": "#2a2a2a",
        "on-surface-variant": "#bbbbbb",
        "outline": "#404040",
        "outline-variant": "#2a2a2a",
        "tertiary": "#76ff03",
        "on-tertiary": "#0d1e00",
        "tertiary-container": "#243610",
        "on-tertiary-container": "#c2e29e",
        "tertiary-fixed": "#b4ff60",
        "tertiary-fixed-dim": "#7da23f",
        "on-tertiary-fixed": "#1a2e00",
        "on-tertiary-fixed-variant": "#466a00",
        "error": "#f2b849",
        "on-error": "#402000",
        "error-container": "#5c3a00",
        "on-error-container": "#ffd080",
        "background": "#000000",
        "on-background": "#d4d0cc",
      },
      fontFamily: {
        "headline-xl": ["Anton"],
        "headline-lg": ["Anton"],
        "headline-lg-mobile": ["Anton"],
        "sticker-label": ["Anton"],
        "body-lg": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "annotation": ["Space Mono"],
        "handwriting": ["Shadows Into Light"],
      },
      fontSize: {
        "headline-xl": ["120px", { lineHeight: "100px", letterSpacing: "-0.04em", fontWeight: "400" }],
        "headline-lg": ["80px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-lg-mobile": ["48px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "sticker-label": ["18px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "annotation": ["14px", { lineHeight: "18px", fontWeight: "400" }],
        "display": ["220px", { lineHeight: "180px", letterSpacing: "-0.04em", fontWeight: "400" }],
      },
      spacing: {
        "tilt-primary": "-2deg",
        "tilt-secondary": "1.5deg",
        "gutter": "16px",
        "unit": "4px",
        "margin-safe": "32px",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
      },
    },
  },
  plugins: [],
};
export default config;